mkdir -p build dest
(cd build && cmake \
	-G 'Unix Makefiles' \
 	-DCMAKE_INSTALL_PREFIX="$PWD/dest" \
 	-DPython_EXECUTABLE=/usr/bin/python3.11 \
 	-DRUBY_EXECUTABLE=/usr/bin/ruby31 \
 	-DBWRAP_EXECUTABLE:FILEPATH=/usr/bin/bwrap \
 	-DDBUS_PROXY_EXECUTABLE:FILEPATH=/usr/bin/xdg-dbus-proxy \
 	-DPORT=GTK \
 	-DENABLE_API_TESTS=OFF \
 	-DENABLE_BUBBLEWRAP_SANDBOX=yes \
 	-DENABLE_GAMEPAD=no \
 	-DENABLE_MINIBROWSER=yes \
 	-DENABLE_PDFJS=no \
 	-DENABLE_GEOLOCATION=ON \
 	-DENABLE_SPELLCHECK=no \
 	-DENABLE_UNIFIED_BUILDS=yes \
 	-DENABLE_VIDEO=no \
 	-DENABLE_WEB_RTC=no \
 	-DUSE_GSTREAMER_WEBRTC=no \
 	-DUSE_GSTREAMER_TRANSCODER=no \
 	-DENABLE_WEBDRIVER=OFF \
 	-DENABLE_WEBGL=OFF \
 	-DENABLE_WEB_AUDIO=no \
 	-DUSE_AVIF=no \
 	-DENABLE_DOCUMENTATION=OFF \
 	-DENABLE_INTROSPECTION=no \
 	-DENABLE_JOURNALD_LOG=no \
 	-DENABLE_QUARTZ_TARGET=no \
 	-DENABLE_WAYLAND_TARGET=no \
 	-DENABLE_X11_TARGET=yes \
 	-DUSE_GBM=ON \
 	-DUSE_GTK4=OFF \
 	-DUSE_JPEGXL=no \
 	-DUSE_LCMS=yes \
 	-DUSE_LIBHYPHEN=ON \
 	-DUSE_LIBSECRET=yes \
 	-DUSE_OPENJPEG=yes \
 	-DUSE_WOFF2=ON \
 	-DUSE_LIBBACKTRACE=OFF \
	-DENABLE_TOUCH_EVENTS=NO \
 	..
)
mkdir -p build/bin/TestWebKitAPI/WebKitGTK/resources
